// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package sqliteStore

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repository (
  id, slug
) VALUES (
  ?, ?
)
RETURNING id, slug
`

type CreateRepositoryParams struct {
	ID   string
	Slug string
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository, arg.ID, arg.Slug)
	var i Repository
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}
